package com.example;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class ExerciseMathTest {

    @BeforeEach
    void setUp() {
    }

    @AfterEach
    void tearDown() {
    }

    @Test
    void testPower1() {
//        double actualAnswer = ExerciseMath.factorial(- 1);
//        IllegalAccessException exception = assertThrows(IllegalAccessException.class, () -> ExerciseMath.factorial(-1));
//        assertEquals("0以下の値は不正です", exception.getMessage(), "TC1:期待値と実際の結果が異なります");
    }
//
//
//    @Test
//    void testPower2() {
//        double actualAnswer = ExerciseMath.factorial(0);
//        IllegalAccessException exception = assertThrows(IllegalAccessException.class, () -> ExerciseMath.factorial(100);
//        assertEquals("100以上の値は不正です", exception.getMessage(), "TC2:期待値と実際の結果が異なります");
//    }
//
//
//    @Test
//    void testPower3(){
//        double actualAnswer = ExerciseMath.factorial(1);
//        assertEquals(1, actualAnswer, "TC3:期待値と実際の結果が異なります");
//    }
//
//    @Test
//    void testPower4(){
//        double actualAnswer = ExerciseMath.factorial(3);
//        assertEquals(6, actualAnswer, "TC4:期待値と実際の結果が異なります");
//    }
//
//    @Test
//    void testPower5(){
//        double actualAnswer = ExerciseMath.factorial(12);
//        assertEquals(6, actualAnswer, "TC4:期待値と実際の結果が異なります");
//    }

}